# Generated by Django 4.1 on 2022-09-04 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentcourse',
            options={'verbose_name_plural': 'Student Course'},
        ),
        migrations.RemoveField(
            model_name='attendanceclass',
            name='status',
        ),
    ]
